/* components/pstar_logging/include/log_macros.h */

#ifndef PSTAR_LOG_MACROS_H
#define PSTAR_LOG_MACROS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Include sdkconfig.h to get the CONFIG_* macros directly */
#include "sdkconfig.h"

/* Macros *********************************************************************/

/* Use CONFIG_* macros directly when available */
/* If not available (older projects), provide backwards compatibility defaults */

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_MAX_MESSAGE_LENGTH
#define CONFIG_PSTAR_KCONFIG_LOGGING_MAX_MESSAGE_LENGTH    (256)
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_MAX_TAG_LENGTH
#define CONFIG_PSTAR_KCONFIG_LOGGING_MAX_TAG_LENGTH        (32)
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_SEPARATOR
#define CONFIG_PSTAR_KCONFIG_LOGGING_SEPARATOR             (" - ")
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_TASK_NAME_LENGTH
#define CONFIG_PSTAR_KCONFIG_LOGGING_TASK_NAME_LENGTH      (16)
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_BUFFER_SIZE
#define CONFIG_PSTAR_KCONFIG_LOGGING_BUFFER_SIZE           (10)
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_TIMESTAMP_BUFFER_SIZE
#define CONFIG_PSTAR_KCONFIG_LOGGING_TIMESTAMP_BUFFER_SIZE (64)
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_DATE_STRING_BUFFER_SIZE
#define CONFIG_PSTAR_KCONFIG_LOGGING_DATE_STRING_BUFFER_SIZE (32)
#endif

/* New macros for log storage */
#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_COMPRESSION_BUFFER_SIZE
#define CONFIG_PSTAR_KCONFIG_LOGGING_COMPRESSION_BUFFER_SIZE (4096)
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_ZLIB_WINDOW_BITS
#define CONFIG_PSTAR_KCONFIG_LOGGING_ZLIB_WINDOW_BITS      (15)
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_ZLIB_MEM_LEVEL
#define CONFIG_PSTAR_KCONFIG_LOGGING_ZLIB_MEM_LEVEL        (8)
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_BASE_DIR
#define CONFIG_PSTAR_KCONFIG_LOGGING_BASE_DIR              ("logs")
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_COMPRESSED_EXTENSION
#define CONFIG_PSTAR_KCONFIG_LOGGING_COMPRESSED_EXTENSION  (".gz")
#endif

#ifndef CONFIG_PSTAR_KCONFIG_LOGGING_MAX_FILE_SIZE_KB
#define CONFIG_PSTAR_KCONFIG_LOGGING_MAX_FILE_SIZE_KB      (1024)
#endif

/* Derived macros */
#define PSTAR_LOGGING_MAX_MESSAGE_LENGTH     CONFIG_PSTAR_KCONFIG_LOGGING_MAX_MESSAGE_LENGTH
#define PSTAR_LOGGING_MAX_TAG_LENGTH         CONFIG_PSTAR_KCONFIG_LOGGING_MAX_TAG_LENGTH
#define PSTAR_LOGGING_SEPARATOR              CONFIG_PSTAR_KCONFIG_LOGGING_SEPARATOR
#define PSTAR_LOGGING_TASK_NAME_LENGTH       CONFIG_PSTAR_KCONFIG_LOGGING_TASK_NAME_LENGTH
#define PSTAR_LOGGING_BUFFER_SIZE            CONFIG_PSTAR_KCONFIG_LOGGING_BUFFER_SIZE
#define PSTAR_LOGGING_TIMESTAMP_BUFFER_SIZE  CONFIG_PSTAR_KCONFIG_LOGGING_TIMESTAMP_BUFFER_SIZE
#define PSTAR_LOGGING_DATE_STRING_BUFFER_SIZE CONFIG_PSTAR_KCONFIG_LOGGING_DATE_STRING_BUFFER_SIZE
#define PSTAR_LOGGING_MAX_FORMATTED_ENTRY_LENGTH (CONFIG_PSTAR_KCONFIG_LOGGING_MAX_MESSAGE_LENGTH * 2)

/* Added derived macros for log storage */
#define PSTAR_LOGGING_MAX_FILE_SIZE          (CONFIG_PSTAR_KCONFIG_LOGGING_MAX_FILE_SIZE_KB * 1024)
#define PSTAR_LOGGING_COMPRESSION_BUFFER     CONFIG_PSTAR_KCONFIG_LOGGING_COMPRESSION_BUFFER_SIZE
#define PSTAR_LOGGING_ZLIB_GZIP_WINDOW_BITS  (CONFIG_PSTAR_KCONFIG_LOGGING_ZLIB_WINDOW_BITS + 16)
#define PSTAR_LOGGING_ZLIB_MEMORY_LEVEL      CONFIG_PSTAR_KCONFIG_LOGGING_ZLIB_MEM_LEVEL
#define PSTAR_LOGGING_BASE_DIRECTORY         CONFIG_PSTAR_KCONFIG_LOGGING_BASE_DIR
#define PSTAR_LOGGING_COMPRESSED_FILE_EXT    CONFIG_PSTAR_KCONFIG_LOGGING_COMPRESSED_EXTENSION

#ifdef __cplusplus
}
#endif

#endif /* PSTAR_LOG_MACROS_H */
